[versions]
kotlin = "2.4.20"
jdk = "25"
minecraft = "26.1.2"
paper = "26.1.2.build.74-stable"
shadow = "9.1.0"

[libraries]
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
